name: Build & Test

on:
  push:
    branches: 
      - main
      - ipv6-support
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['20.x', '21.x', '22.x', '23.x', '24.x', '25.x']
        elixir: ['1.9.x', '1.10.x', '1.11.x', '1.12.x', '1.13.x', '1.14.x']
        exclude:
          - elixir: '1.9.x'
            otp: '23.x'
          - elixir: '1.9.x'
            otp: '24.x'
          - elixir: '1.10.x'
            otp: '20.x'
          - elixir: '1.10.x'
            otp: '24.x'
          - elixir: '1.11.x'
            otp: '20.x'
          - elixir: '1.12.x'
            otp: '20.x'
          - elixir: '1.12.x'
            otp: '21.x'
          - elixir: '1.13.x'
            otp: '20.x'
          - elixir: '1.13.x'
            otp: '21.x'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{matrix.elixir}}
        otp-version: ${{matrix.otp}}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
